#ifndef DOOMRPG_ESP32_NATIVE_MAIN_MENU_160X120_LAYOUT_H
#define DOOMRPG_ESP32_NATIVE_MAIN_MENU_160X120_LAYOUT_H

/* ESP32/CYD presentation contracts for the real Doom RPG main menu.
 *
 * The legacy fitted constants remain for historical/reference paths. The
 * active MENU_MAIN and Options presentations share the finger-first DASH_*
 * geometry below.
 */
#define DOOMRPG_ESP32_MAIN_MENU_LOGO_SRC_WIDTH 108
#define DOOMRPG_ESP32_MAIN_MENU_LOGO_SRC_HEIGHT 74
#define DOOMRPG_ESP32_MAIN_MENU_LOGO_WIDTH 90
#define DOOMRPG_ESP32_MAIN_MENU_LOGO_HEIGHT 62
#define DOOMRPG_ESP32_MAIN_MENU_LOGO_Y 2

#define DOOMRPG_ESP32_MAIN_MENU_ITEM_COUNT 4
#define DOOMRPG_ESP32_MAIN_MENU_ITEM_START_Y 67
#define DOOMRPG_ESP32_MAIN_MENU_ITEM_LINE_HEIGHT 12
#define DOOMRPG_ESP32_MAIN_MENU_FONT_HEIGHT 12

#define DOOMRPG_ESP32_MAIN_MENU_LAST_ITEM_Y \
    (DOOMRPG_ESP32_MAIN_MENU_ITEM_START_Y + \
     ((DOOMRPG_ESP32_MAIN_MENU_ITEM_COUNT - 1) * \
      DOOMRPG_ESP32_MAIN_MENU_ITEM_LINE_HEIGHT))

#define DOOMRPG_ESP32_MAIN_MENU_CONTENT_BOTTOM \
    (DOOMRPG_ESP32_MAIN_MENU_LAST_ITEM_Y + \
     DOOMRPG_ESP32_MAIN_MENU_FONT_HEIGHT)

/* Finger-first MENU_MAIN dashboard. Preserve the proven 90x62 title scale:
 * the logo stays visually dominant while the two card rows remain generous
 * 68x23 logical / 136x46 physical touch targets.
 */
#define DOOMRPG_ESP32_MAIN_MENU_DASH_LOGO_WIDTH 90
#define DOOMRPG_ESP32_MAIN_MENU_DASH_LOGO_HEIGHT 62
#define DOOMRPG_ESP32_MAIN_MENU_DASH_LOGO_Y 2

#define DOOMRPG_ESP32_MAIN_MENU_DASH_RAIL_TOP 64
#define DOOMRPG_ESP32_MAIN_MENU_DASH_RAIL_BOTTOM 65

#define DOOMRPG_ESP32_MAIN_MENU_CARD_COL0_LEFT 8
#define DOOMRPG_ESP32_MAIN_MENU_CARD_COL0_RIGHT 75
#define DOOMRPG_ESP32_MAIN_MENU_CARD_COL1_LEFT 84
#define DOOMRPG_ESP32_MAIN_MENU_CARD_COL1_RIGHT 151
#define DOOMRPG_ESP32_MAIN_MENU_CARD_ROW0_TOP 67
#define DOOMRPG_ESP32_MAIN_MENU_CARD_ROW0_BOTTOM 89
#define DOOMRPG_ESP32_MAIN_MENU_CARD_ROW1_TOP 93
#define DOOMRPG_ESP32_MAIN_MENU_CARD_ROW1_BOTTOM 115
#define DOOMRPG_ESP32_MAIN_MENU_DASH_FOOTER_Y 118

#endif
